build:
  nodes:
    analysis:
      project_setup:
        override:
          - "true"
      tests:
        override:
          - php-scrutinizer-run
          - command: phpcs-run
            use_website_config: true
          - js-scrutinizer-run
          - command: eslint-run
            use_website_config: false
      environment:
        node:
          version: 10.14.1
    tests: true
filter:
  paths:
    - "app/*"
  excluded_paths:
    - "app/views/*"
    - "app/config/*"
    - "app/database/*"
    - "tests/*"
checks:
  php:
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: true
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_identation_4spaces: true
    fix_doc_comments: true
  javascript: true
coding_style:
  php:
    spaces:
      within:
        brackets: true
