language: python

python:
  - "3.6"
  - "3.7"
  - "pypy3.7"

addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11

env:
  global:
    - PGPORT=5433
    - TRAVIS_NODE_VERSION="8"

matrix:
  fast_finish: true

virtualenv:
  system_site_packages: true

notifications:
  email: false

cache:
  yarn: true
  directories:
    - node_modules

services:
  - redis-server

before_script:
  - cp .env.travis .env
  # - do migration

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testing;'

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry yarn install

# script:
#   - pytest
