language: python

addons:
  postgresql: "11"

env:
  - TRAVIS_NODE_VERSION="8" PGPORT=5433

matrix:
  fast_finish: true
  include:
  - name: "Python 3.6"
    python: "3.6"
  - name: "Python 3.7"
    python: "3.7"
  - name: "PyPy 3.7"
    python: "pypy3.7"

virtualenv:
  system_site_packages: true

notifications:
  email: false

cache:
  yarn: true
  directories:
    - node_modules

services:
  - redis-server

before_script:
  - cp .env.travis .env
  # - do migration

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testing;'

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry yarn install

# script:
#   - pytest
