language: python

addons:
  mariadb: "10.3"

env:
  - TRAVIS_NODE_VERSION="8"

matrix:
  fast_finish: true
  include:
    - php: "3.6"
    - php: "3.7"

notifications:
  email: false

cache:
  yarn: true
  directories:
    - node_modules

services:
  - redis-server

before_script:
  - cp .env.travis .env
  # - do migration

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testing;'

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry yarn install

# script:
#   - vendor/bin/phpunit --coverage-text
