language: python

sudo: false

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - postgresql-contrib-10

env:
  - TRAVIS_NODE_VERSION="8" PGPORT=5433

matrix:
  fast_finish: true
  include:
  # - python: "3.7.1"
  - python: "3.6.7"
  - python: "pypy3.5"

# virtualenv:
#   system_site_packages: true

notifications:
  email: false

cache:
  yarn: true
  directories:
    - $HOME/virtualenv
    - node_modules

services:
  - redis-server

before_script:
  - cp .env.travis .env
  # - do migration

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
  - psql -p 5433 -U postgres -c "CREATE DATABASE testing;"
  - psql -p 5433 -U postgres -c "CREATE USER foo WITH PASSWORD 'bar';"
  - psql -p 5433 -U postgres -c "CREATE EXTENSION 'uuid-ossp';"

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry yarn install

# script:
#   - pytest
