language: python

dist: xenial

sudo: true

addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
    - postgresql-contrib-11

env:
  - TRAVIS_NODE_VERSION="8" PGPORT=5433 PGUSER=postgres

matrix:
  fast_finish: true
  include:
  - python: "3.6"
  - python: "3.7"
  # - python: "pypy3.5"

# virtualenv:
#   system_site_packages: true

notifications:
  email: false

cache:
  yarn: true
  directories:
    - $HOME/virtualenv
    - node_modules

services:
  - redis-server

before_install:
  - curl -o- -sL https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH

  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart && sleep 1

  - psql -p $PGPORT -U $PGUSER -c "CREATE DATABASE testing;"
  - psql -p $PGPORT -U $PGUSER -c "CREATE USER foo WITH PASSWORD 'bar';"
  - psql -p $PGPORT -U $PGUSER -c 'CREATE EXTENSION "uuid-ossp";'

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry yarn install

before_script:
  - cat .env.travis > .env
  # - do migration

script:
  - echo "All process has been complete!"
#   - pytest
