language: python

sudo: false

addons:
  postgresql: "11"
  # apt:
  #   packages:
  #   - postgresql-11
  #   - postgresql-client-11
  #   - postgresql-contrib-11

env:
  - TRAVIS_NODE_VERSION="8" PGPORT=5433

matrix:
  fast_finish: true
  include:
  - python: "3.6.7"
  - python: "3.7.1"
  - python: "pypy3.5"

# virtualenv:
#   system_site_packages: true

notifications:
  email: false

cache:
  yarn: true
  directories:
    - $HOME/virtualenv
    - node_modules

services:
  - redis-server

before_script:
  - cp .env.travis .env
  # - do migration

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq && sudo apt-get install -yqq yarn
  - psql -U postgres -c "CREATE DATABASE testing;"
  - psql -U postgres -c "CREATE USER foo WITH PASSWORD 'bar';"
  - psql -U postgres -c "CREATE EXTENSION 'uuid-ossp';"

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry yarn install

# script:
#   - pytest
